version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: EvansAutoParts-db
    restart: always
    environment:
      POSTGRES_USER: EvansAutoParts_admin
      POSTGRES_DB: EvansAutoParts
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
